server:
    port: 8083

env:
    output: src/main/resources/output/customers.csv

spring:
    output:
        ansi:
            enabled: ALWAYS

    main:
        allow-bean-definition-overriding: true

    rabbitmq:
        host: localhost
        port: 5672
        username: batch
        password: batch
        routingkey: batch.new-customer
        exchange: amq.direct
        queue: batch.queue

    batch:
        job:
            enabled: false
        jdbc:
            initialize-schema: ALWAYS

    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3308/customer-service?serverTimezone=UTC
        username: root
        
    jpa:
        hibernate:
            ddl-auto: create-drop
        show-sql: false
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
                format_sql: true